# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd5bbfd81d9808be15e4592f4d3c5687c29456e5da92503cc2c9892d2c58be9769ad9bd26edb127c88e12657047871dff9f22b6a19a5e0b0a03a3541983edd9b

test:
  secret_key_base: 054fa00bc47d8e864dedb23f08f1aac093c8b2d8accd92d2e3cee7b7d46c967acc16cc299f2cfab8027d4bd1c0f1cc109c06f74867d48003bdb0110f4688a681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
